### ISSUE TITLE
Sth broke badly

### ISSUE THREAD

**Issue by tszirr** [Perlmint/glew-cmake#11]
Hey,

just had loads of build errors pop up, seems like sth went rather wrong, e.g. glew.c now features garbage like this:
static GLboolean _glewInit_GL_ARB_ES3_1_compatibility ()
{
  GLboolean r = GL_FALSE;

  r = _glewInit_(GLbitfield() || r;
  r = _glewInit_barriers)() || r;
  r = _glewInit_glMemoryBarrierByRegion() || r;
  r = _glewInit_void() || r;

  return r;
}
Any ideas?

Thx!

**Comment by Perlmint** [comment]
Thanks for reporting.  
I cleaned up my CI workspace, run update source job and code generating.
Now, It is built without error.  
Try again with updated source please.

**Comment by tszirr** [comment]
Thanks for the quick response, has worked flawlessly since then.
