### ISSUE TITLE
Import tags as well as commits from the source repo

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Perlmint/glew-cmake#19]
It makes the project seem badly out of date, since the tags denote GLEW releases.

**Comment by Perlmint** [comment]
I just updated maintain script in a7405131ff18f6eaf33e681f3ff8aefb6a924589. 
If this is working well at the nightly update, I'll close this issue.

**Comment by Perlmint** [comment]
It will be automatically imported.
