### ISSUE TITLE
Trigger update when KhronosGroup/OpenGL-Registry is updated?

### ISSUE THREAD

**Issue by nigels-com** [Perlmint/glew-cmake#21]
In relation to a pending issue upstream:
https://github.com/nigels-com/glew/issues/235

It would be handy to trigger a (possible) update of Perlmint/glew-cmake when OpenGL-Registry is updated, or perhaps nightly or weekly to limit resource consumption.

**Comment by Perlmint** [comment]
Thanks for suggestion. But, It is hard to apply this.

I have a plan to fix nightly update by moving CI(#23). After moving, triggering the job by checking update the other repo(OpenlGL-Registry) will be impossible - not supported.

**Comment by nigels-com** [comment]
Fair enough.  Multi-repo dependencies do tend to make life more complicated.

**Comment by Perlmint** [comment]
From now, try to update nightly. :)

**Comment by nigels-com** [comment]
Awesome!  Thanks.
