### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by DieSlower** [Perlmint/glew-cmake#22]
Hello,

On the main page it says that the version of the project is up to release 2.1.0
But there is no tag that corresponds to it. 
Could one be made please?

V/R,
--Maxim

**Comment by Perlmint** [comment]
It was generated, but I removed them because it had wrong contents - see #20. I'm working on it to generate correctly.
After generate correct releases, I'll close this issue.

**Comment by Perlmint** [comment]
Miss clicked. Sorry.

**Comment by DieSlower** [comment]
Ok,

Thank you Gyusun!

**Comment by Perlmint** [comment]
All tags are imported!

**Comment by DieSlower** [comment]
Now I'm getting this errors when I run cmake with VS2019

CMake Error at CMakeLists.txt:85 (ADD_LIBRARY):
  Cannot find source file:

    D:/Development/ExtDev/Build/glew-cmake-glew-cmake-2.1.0/build/glew.rc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:85 (ADD_LIBRARY):
  No SOURCES given to target: libglewmx_shared


CMake Error at CMakeLists.txt:45 (ADD_LIBRARY):
  No SOURCES given to target: libglew_static


CMake Error at CMakeLists.txt:70 (ADD_LIBRARY):
  No SOURCES given to target: libglew_shared


CMake Error at CMakeLists.txt:56 (ADD_LIBRARY):
  No SOURCES given to target: libglewmx_static

**Comment by DieSlower** [comment]
Yep, that seemed to work! Thank you!
Will these changes be merged into the https://github.com/nigels-com/glew repo by any chance?

**Comment by Perlmint** [comment]
I don't know what the theses changes precisely is. If you mean a fixing build error refered here, It may not be merged to original glew repo. As I know, Original glew repo does not provide pre-generated glew source codes by git. But these errors are related to wrong pre-generated source codes.

**Comment by DieSlower** [comment]
From what I remember the original does have a cmake script that can be used to generate the VS project for yourself. 
https://github.com/nigels-com/glew/tree/glew-2.1.0/build/cmake
But the original repo still has no support for VS2019, which you have fixed here. 
So if your fixes make it back to the original, that would be amazing!

**Comment by Perlmint** [comment]
The error you have experienced is not related to VS2019, and It was about missing file referred in CMakeLists.txt.
If you tried to generate a project with cmake of original glew from git, It is a wrong way to build glew. Original glew git doesn't contain header files & source files, resource files, So it recommends to use compressed official release - [details here](https://github.com/nigels-com/glew/blob/glew-2.1.0/README.md#build), you can download from [here (glew-2.1.0.tgz)](https://github.com/nigels-com/glew/releases).
If you had experienced the same error with the compressed official release, please notify me, I'll check it and try to fix original :)

**Comment by DieSlower** [comment]
Ah...interesting... 
I used to be able to build the official release using VS2017 by following this:
https://github.com/acidrainstudios/TrueReality/wiki/Building-Windows-VS2017-External-Dependencies
I would download glew source from:
https://sourceforge.net/projects/glew/files/glew/2.1.0/

This was a while ago, but it used to build and work great. When I tried it recently with VS2019 it failed. That's when I reached out to Nigel and yourself. 

Thank you for your help!

**Comment by nigels-com** [comment]
For what it's worth, the GLEW cmake build is user-contributed.
I don't tend to use or test that path.  (It's a .c file, after all)

I ought to revisit AppVeyour to see if that is able to build end-to-end on Windows.
Contributions are of course welcome, especially with an intended upcoming release.

**Comment by DieSlower** [comment]
@nigels-com 
Aha! Well, @Perlmint s cmake files work great! Maybe they can be added to the new release?

**Comment by nigels-com** [comment]
That's worth considering, but I also need to weigh the potential fall-out if they're somehow different to the status quo.  Time to give the Windows laptop a spin, I guess.

**Comment by DieSlower** [comment]
@nigels-com Off course! Test, test and retest! :)
Hope it all pans out!

**Comment by nigels-com** [comment]
Yeah, endless testing is not a _feature_ of cmake, it's a _bug_.  (grumble, grumble!)
