### ISSUE TITLE
[pkg-config] glew.pc.in is not processed

### ISSUE THREAD

**Issue by 5schatten** [Perlmint/glew-cmake#24]
Some stuff like https://github.com/freedesktop/mesa-demos still relies on pkg-config to detect installed libs & headers so it would be useful if your CMake build could process & install the glew.pc.in file too.

**Comment by Perlmint** [comment]
I pushed a trial as [feature/pkgconfig branch](https://github.com/Perlmint/glew-cmake/tree/feature/pkgconfig). New CMake file in this trial will generate a pc file for each target. Also, you can specify a representative target with PKG_CONFIG_REPRESENTATIVE_TARGET option to use with `glew` name.
I'm not familiar with pkg-config. So, I don't guarantee it works correctly. Before merging it to master, Could you test it?

**Comment by 5schatten** [comment]
Thanks for looking into this but could you base it on top of glew 2.1? Your latest master branch does not compile for me https://pastebin.com/7Qe27203 :thinking:

**Comment by Perlmint** [comment]
Thanks for detail comment! :+1: 

I have a question.
Has `Name` in pkg-config a special behaviour? If it is just an identifier - have no change in pkg-config behaviour, I think keeping them - 4 targets be built - different can be useful. If you need the name `glew`, `PKG_CONFIG_REPRESENTATIVE_TARGET` can be helpful.

Also, I fixed you commented.
Here is a generated glew.pc with `PKG_CONFIG_REPRESENTATIVE_TARGET=libglew_static`
```plain
prefix=/usr/local
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: glew
Description: The OpenGL Extension Wrangler library
Version: 2.2.0
Cflags: -I${includedir} -DGLEW_STATIC
Libs: -L${libdir} -llibglew.a -lGL -lX11 -ldl -lXext
```

**Comment by 5schatten** [comment]
According too https://people.freedesktop.org/~dbn/pkg-config-guide.html
`Name: A human-readable name for the library or package. This does not affect usage of the pkg-config tool, which uses the name of the .pc file.` so I guess it's fine if you use a custom name too :+1: 

I'll test it later then and see if I run into any issues.

**Comment by Perlmint** [comment]
I found `-llibglew.so` is a portable way to link with a specific name. But it seems not working. I give up to provide proper pc files for all targets. Make it generate the only glew.pc.

About GLU, I didn't notice it should be a PUBLIC definition. I moved it to PRIVATE definitions. Now it will propagate to other targets link to glew when USE_GLU is set, Or cmake checks the GLU exists when USE_GLU is not set.

glew.pc - single context, static, no_glu
```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: glew
Description: The OpenGL Extension Wrangler library
Version: 2.2.0
Cflags: -I${includedir} -DGLEW_STATIC -DGLEW_NO_GLU
Libs: -L${libdir} -lglew -lGL -lX11 -ldl -lXext
```

**Comment by 5schatten** [comment]
I made some tests and lgtm. I'll start a clean build and see if I run into any issues.

**Comment by 5schatten** [comment]
Works fine here :+1:  so closed by these additions https://github.com/Perlmint/glew-cmake/tree/feature/pkgconfig

**Comment by Perlmint** [comment]
@cnDelbert `feature/pkgconfig` branch was merged into `master` branch. Also, pkg-config does not use `.pc.in` file. it is a template to generate `.pc`file. Also, `.pc.in` file is not used in glew-cmake. It is used in [original glew](https://github.com/nigels-com/glew).
If you want to use glew-cmake with pkg-config, please build it and install it with CMake command (use `CMakeLists.txt` in the root of this repository).
