### ISSUE TITLE
Rewriting history changes git hashes/commit IDs cannot use your repo as a submodule reliably.

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Perlmint/glew-cmake#26]
You have neither up-to-date / reliable tags or commit IDs that don't change, every single time you pull/update from whatever cmake repo you use as source, the commit IDs change and projects using your repository as a submodule get an error about "unadvertised object"s.

**Comment by Perlmint** [comment]
First of all, I apologise for rewriting some tags/commits. But, I should update some wrong tags and commits - contained incorrect contents(#20). I should update some objects forcibly around Sep 2019.

At now, update script works correctly. I think that this will not occur anymore.

**Comment by devshgraphicsprogramming** [comment]
It seems to happen at least once every 1-2 months from our end

**Comment by Perlmint** [comment]
Did you suffer this issue with the commits created after Sep 22?

Tags were rewritten at Sep 18, 2019, as you can see at https://github.com/Perlmint/glew-cmake/releases. And, there is a possibility of a forced push to master on Sep 22. Update script does not have any forced push commands.

If you did, Please tell me commits which are related. Anyway, I'll keep in mind this for after work.

**Comment by Perlmint** [comment]
No update - close.
