### ISSUE TITLE
What is the purpose of BUILD_MULTI_CONTEXT?

### ISSUE THREAD

**Issue by drywolf** [Perlmint/glew-cmake#27]
As the title says I can't seem to figure out what the BUILD_SINGLE_CONTEXT/BUILD_MULTI_CONTEXT options actually do.
Furthermore, the target-properties `OUTPUT_NAME` do overlap for those targets, so in essence there is a race condition for the build whichever target finished building last wins and will write the final lib file, and hence the build result is indeterministic if both those options are active at the same time.

@Perlmint Can you please clarify what those are for. Thanks

**Comment by Perlmint** [comment]
After reading this issue and some investigation, I realised those options are no longer valid. Please ignore those options.
I just found there is no MX after glew 2.0 - see [changelog of glew](http://glew.sourceforge.net/log.html).
I'll remove invalid options & build targets.

Thanks for reporting :)

**Comment by drywolf** [comment]
Thanks for the clarification 👍
