### ISSUE TITLE
Use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR

### ISSUE THREAD

**Issue by Gpinchon** [Perlmint/glew-cmake#29]
Using CMAKE_SOURCE_DIR makes it so the library is built in the wrong directory when added to the project via FetchContent and then adding it using something like `add_subdirectory(${glew_SOURCE_DIR} ${glew_BINARY_DIR})`

**Comment by Perlmint** [comment]
First of all, Thanks for piling an issue.
I'm sorry, But I can't find a point using CMAKE_SOURCE_DIR - only used in [here](https://github.com/Perlmint/glew-cmake/blob/master/CMakeLists.txt#L103) - possibly occurring error on the master branch. Can you specify the actual point?

**Comment by Gpinchon** [comment]
Sorry, I meant CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR.
But after investigating, I think it's even better to avoid setting CMAKE_ARCHIVE_OUTPUT_DIRECTORY, CMAKE_LIBRARY_OUTPUT_DIRECTORY and CMAKE_RUNTIME_OUTPUT_DIRECTORY altogether, as it keeps parent projects from choosing where to put glew's files.

**Comment by Gpinchon** [comment]
I did a fork, do you want me to do a PR ?

**Comment by Perlmint** [comment]
If you can make a PR, I will appreciate it.
