### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by cecabert** [Perlmint/glew-cmake#33]
When cloning the branch `glew-cmake-release` the `CMakeFiles.txt` script will crash at line 12 trying to execute `include("GeneratePkgConfig.cmake")` since the file is missing.

**Comment by SupervisedThinking** [comment]
Build log:
https://pastebin.com/FDq21xWR

**Comment by Perlmint** [comment]
Thanks!
I updated maintaining script. And removed the not working tag glew-cmake-2.2.0.
When it is generated automatically - by the daily update, I'll close this issue.

**Comment by cecabert** [comment]
By the way, the version is also missing.

**Comment by Perlmint** [comment]
> By the way, the version is also missing.

I removed them to be generated by daily update. Now, 2.2.0 tags are re-generated.
