### ISSUE TITLE
config/version is missing in v2.2.0

### ISSUE THREAD

**Issue by SupervisedThinking** [Perlmint/glew-cmake#34]
https://pastebin.com/1BZc3g0h

add this

https://github.com/Perlmint/glew-cmake/blob/master/config/version

by

https://github.com/Perlmint/glew-cmake/pull/35

**Comment by Perlmint** [comment]
Thanks! [2.2.0](https://github.com/Perlmint/glew-cmake/tree/glew-cmake-2.2.0) is re-released! It has config/version now.
