### ISSUE TITLE
libglew instead of libGLEW / add symlink

### ISSUE THREAD

**Issue by SupervisedThinking** [Perlmint/glew-cmake#36]
It looks like the usual distributions ship glew as `libGLEW.so` instead of `libglew.so` which should be no problem as long as the pkg-config files is used to determine linker flags. 

https://github.com/archlinux/svntogit-packages/blob/packages/glew/trunk/PKGBUILD#L13

But some programs have a hardcoded lib detection like this:

https://github.com/duganchen/dosbox/blob/master/configure.ac#L469-L471

Could you add a symlink `libGLEW.so` to `libglew.so` for compatibility purposed? I guess this will be just a single line of code.

**Comment by Perlmint** [comment]
@SupervisedThinking Can you test #37 is working, please?

**Comment by SupervisedThinking** [comment]
LGTM: should be fixed by https://github.com/Perlmint/glew-cmake/pull/37
