### ISSUE TITLE
set a cmake policy

### ISSUE THREAD

**Issue by Jtaim** [Perlmint/glew-cmake#39]
I'm using as submodule in my project using CMAKE version 3.19.4.  Get a warning about CMP0048.

Can a policy be set in glews CMakeLists.tx to supress this warning?
[CMakeLists.txt](https://github.com/Perlmint/glew-cmake/files/5937262/CMakeLists.txt)

 cmake_minimum_required(VERSION 2.8.12)

if (POLICY CMP0048)
    cmake_policy(SET CMP0048 NEW)
endif()

project("glew")

**Comment by Perlmint** [comment]
Thank you for the suggestion.
I changed the way of specifying the project version in a new way and set CMP0048 new.
It is included in [PR](https://github.com/Perlmint/glew-cmake/pull/42).
