### ISSUE TITLE
Compilation error on macOS regarding symlinks

### ISSUE THREAD

**Issue by janekb04** [Perlmint/glew-cmake#41]
After one of the commits regarding symlinks, the library seems to no longer compile on macOS. [This Github Action run](https://github.com/janekb04/glfwpp/actions/runs/551172659) was performed on commit [7d525405e6abd0933f1a44c066645caea805f5d5](https://github.com/Perlmint/glew-cmake/tree/7d525405e6abd0933f1a44c066645caea805f5d5) (before symlinks where intoduced). It compiles fine on Ubuntu and on macOS. On the other hand, [this run](https://github.com/janekb04/glfwpp/actions/runs/551065931) uses [the most recent commit](https://github.com/Perlmint/glew-cmake/tree/0be1dc6b896f50e33e35e987508eeb50203938aa) and fails. The errors are:
```
[  9%] Linking C static library lib/libglew.a
create libGLEW symbolic link
make[3]: stat: external/glew-cmake/lib/libglew.a: Too many levels of symbolic links
[  9%] Built target libglew_static
```
and
```
Scanning dependencies of target glfwpp_example_basic
[ 86%] Building CXX object examples/CMakeFiles/glfwpp_example_basic.dir/basic.cpp.o
make[3]: stat: external/glew-cmake/lib/libglew.a: Too many levels of symbolic links
make[3]: *** No rule to make target `external/glew-cmake/lib/libglew.a', needed by `examples/glfwpp_example_basic'.  Stop.
```
It seems that one of the commits regarding symlinks broke something, though it's hard for me to tell which one.

**Comment by Perlmint** [comment]
Thank you for reporting the error!
macOS uses the case-insensitive file system as default. It occurs this error.
I created [PR](https://github.com/Perlmint/glew-cmake/pull/42) fixing this. It'll work with cmake macOS. If you don't mind, can you test it works on your environment?

**Comment by janekb04** [comment]
Great, after changing to the new branch [it works](https://github.com/janekb04/glfwpp/actions/runs/551557622) now.
