### ISSUE TITLE
glew not building as a submodule

### ISSUE THREAD

**Issue by SumitKumar1307** [Perlmint/glew-cmake#44]
we have added glew as a submodule in our project and after generating with cmake using ninja when i try to build it in vs code i get an error
`[build] lib/glew-cmake/CMakeFiles/libglew_shared.dir/src/glew.c.obj:glew.c:(.text+0x2f0d1): multiple definition of 'DllMainCRTStartup'
[build] D:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o:crtdll.c:(.text+0x330): first defined here
` i know that this is specific to windows users after looking at glew.c but i have not been able to solve it, any help would be appreciated

**Comment by Perlmint** [comment]
Thanks for reporting an issue.  
In the investigation, This is not an issue about submodule nor windows. It is against MinGW.
Could you test https://github.com/Perlmint/glew-cmake/pull/45 on your environment, please?
