### ISSUE TITLE
How to use EGLEW in Linux ?

### ISSUE THREAD

**Issue by Gpinchon** [Perlmint/glew-cmake#66]
I'm trying to use EGL on Linux and on linking it cannot find any of EGLEW symbols.
Are they only defined in the shared libraries ? Up to this point I only linked against GLEW's static libs...
Am I missing something there ?

[EDIT] After looking a bit more it seems there is no support for EGL, is there a reason for this ?

**Comment by nigels-com** [comment]
GLEW needs to build in EGL mode, -DGLEW_EGL=1
